hydra:
  run:
    dir: .
  output_subdir: null

exp_name: "qwen-sft-config"
seed: 42
logging_dir: ./output/logs
output_dir: ./output_sft
# system_envs:
#   USE_MODELSCOPE: '1'

#track_with: wandb
#tracker_kwargs:
#  api_key:
#  project: roll_examples
#  notes: roll_examples
#  tags:
#    - sft
#    - baseline

track_with: tensorboard
tracker_kwargs:
  log_dir: /home/chenkaiyuan/ROLL-RL/users/tensorboard/roll_exp/agentic_sft

checkpoint_config:
  type: file_system
  output_dir: /home/chenkaiyuan/models/sft-ckpt/${exp_name}

num_gpus_per_node: 8

save_steps: 25
logging_steps: 1
eval_steps: 10
resume_from_checkpoint: false

sequence_length: 20000

pretrain: /home/chenkaiyuan/.cache/huggingface/hub/models--Qwen--Qwen3-4B-Instruct-2507/snapshots/cdbee75f17c01a7cc42f958dc650907174af0554

# sft related 
# system_key: system_prompt # use the default system prompt in the tokenizer tmplate if not provided
prompt_key: instruction
query_key: input
response_key: output
message_key: messages

# validation:
#   data_args:
#     file_name: data/code_alpaca_20k.json
#     template: native

sft_train:
  model_args:
    dtype: bf16
  training_args:
    num_train_epochs: 3
    per_device_train_batch_size: 2
    gradient_accumulation_steps: 64
    learning_rate: 1.0e-5
    # warmup_steps: 0
    warmup_ratio: 0.1
    lr_scheduler_type: cosine
  data_args:
    file_name: /home/chenkaiyuan/evaluation_datasets/tool_sft_processed.jsonl
    template: native
    preprocessing_num_workers: 4
  strategy_args:
    strategy_name: megatron_train
    strategy_config:
      tensor_model_parallel_size: 4
      pipeline_model_parallel_size: 1
      expert_model_parallel_size: 1
      use_distributed_optimizer: true
      sequence_parallel: true
      # context_parallel_size: 2
  device_mapping: list(range(0,4))
  infer_batch_size: 2
